server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: parking-service
          uri: lb://PARKING-SERVICE
          predicates:
            - Path=/api/spaces/**
        - id: vehicle-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/vehicles/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    gateway:
      enabled: true  # Explicitly enable gateway actuator
  endpoints:
    web:
      exposure:
        include: api-gateway  # Expose gateway endpoints