spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eco_parking
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: payment_service
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 2000
      validation-timeout: 5000
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    default-schema: payment_service
    check-location: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: payment_service
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true

server:
  port : 8087